list: $/dmitrychuvakov/planb/models/vote/columns.yaml
modelClass: DmitryChuvakov\Planb\Models\Vote
title: Votes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
